### PR TITLE
RK-11418 - Dark tray icon

### PR DESCRIPTION
**Pull request by lirook**
This adds support for a dark tray icon in MacOS

### CODE REVIEW

**Review by dan505512 — APPROVED** [review]

**Comment by ElDuderinos** [comment]
@lirook is this still relevant?

**Comment by lirook** [comment]
@dudiRookout yes it is, but my tests are failing

**Comment by lirook** [comment]
@dan505512 could you help me with the failing tests?

**Comment by dan505512** [comment]
@lirook I don't know what to tell you. It shouldn't affect the tests so it's just general flakiness

**Comment by dan505512** [comment]
image
Wait what

**Comment by lirook** [comment]
@dan505512 magic, what did you do?

**Comment by dan505512** [comment]
I did some magic @lirook

**Pull request merged**
