### PR TITLE
RK-10697 - Security - fix Nov21 snyk vulns

### PR DESCRIPTION
**Pull request by moryakub**
webapp:
1. move react-scripts to devDependencies so snyk won't show vulns of it as it is used in the build process only
2. clean package.json:
a. removed unsued `uuid` pacakge
b. removed unused `node-sass` package as we do not use scss here
c. removed unused `material-ui/icons` as we do not use it here
3. Upgrade material-ui from latest v1 that had a vuln, to latest v4 (and fixed the minor UI code that we have here)
4. I deleted a component `OnPremConnection` that was `hidden` for a year (and all the comp. it used) and also removed lots of code from `ReposList` which was not needed.

server:
bump xss package version

---
I validated that loading local repos still works.

### CODE REVIEW

**Comment by moryakub** [comment]
RK-10697 RK-10696

**Comment by Gilwe** [comment]
what linter are you using? all you node PRs do not allow more than one statement in one line, that's kinda verbose in terms of line numbers

**Comment by Gilwe** [comment]
also, codeql

**Comment by Gilwe** [comment]
third thing, if you are removing most of the webapp, can you go over the dependencies again and see if there are more which aren't used

**Comment by moryakub** [comment]
@Gilwe
1. I removed everything possible from the package.json
2. regarding linting, can you point at a specific part it happen? this is all React changes

**Review by ron-rookout — APPROVED** [review]

**Comment by Gilwe** [comment]
> @Gilwe
> 
> 1. I removed everything possible from the package.json
> 2. regarding linting, can you point at a specific part it happen? this is all React changes


Screen Shot 2021-11-15 at 14 22 10

what is `React changes`? this is js changes that something automatically changes your code.
it is only in your PRs

**Comment by moryakub** [comment]
@Gilwe i meant that this PR contains only changes in React, and not in node.
and the IMG is of a css file, if you try to prettify it on your machine, does it change it?

**Review by Gilwe — APPROVED** [review]

**Pull request merged**
