### PR TITLE
RK-19885 - Upgrade electron-builder and updater

### PR DESCRIPTION
**Pull request by Urook**
Upgrade electron-builder and electron-updater
Removed patch because:
* It was created in #167 to address [this](https://github.com/electron-userland/electron-builder/issues/4701)
* It looks like the vulnerability was fixed by them around version 5.0.0 via adding reject function to handleError and throwing/rejecting on stderr (as well as rejecting/throwing an error in a certain catch clause)

### CODE REVIEW

**Review by dan505512 — APPROVED** [review]

**Comment by dan505512** [comment]
We can't get anything to build at the moment so I don't think we need to. Once we get the artifacts in a draft release we'll test @Urook

**Comment by Urook** [comment]
@dan505512 Cool.
Who knows, maybe this will even fix the auto update errors we constantly have, the prev version is ~3 years old

**Comment by dan505512** [comment]
> @dan505512 Cool.
> Who knows, maybe this will even fix the auto update errors we constantly have, the prev version is ~3 years old

בעז"ה

**Pull request merged**
